// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk-ScskMw78q6zXckRxcB8urBGqPjcKjA',
    appId: '1:708253295937:web:19bb178875e310e3d32dc0',
    messagingSenderId: '708253295937',
    projectId: 'miabesante-e5456',
    authDomain: 'miabesante-e5456.firebaseapp.com',
    storageBucket: 'miabesante-e5456.appspot.com',
    measurementId: 'G-1N63KRVWCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdfQs141wFIuyAbFQW0vEX8A6kumc6_1A',
    appId: '1:708253295937:android:de223cac85f48cb8d32dc0',
    messagingSenderId: '708253295937',
    projectId: 'miabesante-e5456',
    storageBucket: 'miabesante-e5456.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYMxPT7btGgAlIwFQT7JneHhABsCq9rqc',
    appId: '1:708253295937:ios:7092f901d61f0822d32dc0',
    messagingSenderId: '708253295937',
    projectId: 'miabesante-e5456',
    storageBucket: 'miabesante-e5456.appspot.com',
    iosBundleId: 'com.example.miabesante',
  );
}
